Repository lidofinance/core, pull requests merged in 2020-12, with the labels that each got.

#226 Move signing keys selection to NodeOperatorsRegistry
  contracts/0.4.24/Lido.sol
  contracts/0.4.24/interfaces/INodeOperatorsRegistry.sol
  contracts/0.4.24/lib/MemUtils.sol
  contracts/0.4.24/nos/NodeOperatorsRegistry.sol
  contracts/0.4.24/nos/test_helpers/PoolMock.sol
  contracts/0.4.24/nos/test_helpers/TestNodeOperatorsRegistry.sol
  gasprofile/tx-deposit.js
  test/0.4.24/lido.test.js
  test/0.4.24/node-operators-registry.test.js
  test/helpers/utils.js
Labels: enhancement, solidity

#232 Unstuctured storage variable hash strings and renamings
  apps/lido/app/src/App.js
  apps/lido/app/src/index.js
  apps/lido/app/src/script.js
  apps/lido/scripts/buidler-hooks.js
  contracts/0.4.24/Lido.sol
  contracts/0.4.24/StETH.sol
  contracts/0.4.24/interfaces/IDepositContract.sol
  contracts/0.4.24/interfaces/ILido.sol
  contracts/0.4.24/interfaces/INodeOperatorsRegistry.sol
  contracts/0.4.24/lib/Pausable.sol
  contracts/0.4.24/nos/NodeOperatorsRegistry.sol
  contracts/0.4.24/oracle/LidoOracle.sol
  contracts/0.4.24/test_helpers/DepositContractMock.sol
  contracts/0.4.24/test_helpers/LidoPushableMock.sol
  contracts/0.4.24/test_helpers/TestLido.sol
  estimate_deposit_loop_gas.js
  lib/src/dao.js
  test/0.4.24/lido.test.js
  test/0.4.24/steth.test.js
  test/0.6.12/csteth.test.js
  test/scenario/helpers/deploy.js
  test/scenario/lido_deposit_iteration_limit.js
  test/scenario/lido_happy_path.js
  test/scenario/lido_penalties_slashing.js
Labels: cosmetic, solidity

#274 Fix oracles EOFError when DAEMON set to 0
  e2e/docker-compose.yml
Labels: bug
