Repository lidofinance/core, pull requests merged in 2024-09, with the labels that each got.

#166 feat: allow scratch deploy usage in local integration tests
  .env.example
  .github/workflows/tests-integration-mainnet.yml
  .github/workflows/tests-integration-scratch.yml
  .gitignore
  CONTRIBUTING.md
  docs/scratch-deploy.md
  docs/upgrade-deploy.md
  globals.d.ts
  hardhat.config.ts
  lib/contract.ts
  lib/deploy.ts
  lib/ens.ts
  lib/event.ts
  lib/index.ts
  lib/log.ts
  lib/protocol/context.ts
  lib/protocol/networks.ts
  lib/scratch.ts
  lib/state-file.ts
  package.json
  scripts/dao-ci-deploy.sh
  scripts/dao-deploy.sh
  scripts/dao-local-deploy.sh
  scripts/dao-local-upgrade.sh
  scripts/dao-upgrade.sh
  scripts/scratch/dao-deploy.sh
  scripts/scratch/scratch-acceptance-test.ts
  scripts/scratch/steps.json
  scripts/scratch/steps/00-populate-deploy-artifact-from-env.ts
  scripts/scratch/steps/01-deploy-deposit-contract.ts
  scripts/scratch/steps/02-deploy-aragon-env.ts
  scripts/scratch/steps/03-deploy-template-and-app-bases.ts
  scripts/scratch/steps/04-register-ens-domain.ts
  scripts/scratch/steps/05-deploy-apm.ts
  scripts/scratch/steps/06-create-app-repos.ts
  scripts/scratch/steps/07-deploy-dao.ts
  scripts/scratch/steps/08-issue-tokens.ts
  scripts/scratch/steps/09-deploy-non-aragon-contracts.ts
  scripts/scratch/steps/10-gate-seal.ts
  scripts/scratch/steps/11-finalize-dao.ts
  scripts/scratch/steps/12-initialize-non-aragon-contracts.ts
  scripts/scratch/steps/13-grant-roles.ts
  scripts/scratch/steps/14-plug-curated-staking-module.ts
  scripts/scratch/steps/15-transfer-roles.ts
  scripts/upgrade/steps.json
  scripts/upgrade/steps/00-deploy-locator.ts
  scripts/utils/migrate.ts
  test/0.8.9/oracle/hashConsensus.setQuorum.test.ts
  tsconfig.json
Labels: enhancement, tests

#136 Accounting Oracle integration tests
  lib/protocol/discover.ts
  lib/protocol/helpers/accounting.ts
  lib/protocol/helpers/index.ts
  lib/protocol/networks.ts
  lib/protocol/types.ts
  lib/time.ts
  scripts/scratch/scratch-acceptance-test.ts
  test/0.4.24/nor/nor.rewards.penalties.flow.test.ts
  test/common/math256.t.sol
  test/integration/accounting.ts
Labels: tests

#198 Add sepolia deposit adapter
  contracts/testnets/sepolia/SepoliaDepositAdapter.sol
  test/testnets/sepolia/sepolia-deposit-adapter.test.ts
Labels: contracts, tests

#213 docs: update contribution guide
  CONTRIBUTING.md
  docs/scratch-deploy.md
  package.json
  poetry.lock
  test/integration/accounting.integration.ts
  test/integration/burn-shares.integration.ts
  test/integration/protocol-happy-path.integration.ts
  yarn.lock
Labels: documentation, dependencies

#217 ci: use lidofinance/hardhat-node as a base node for CI actions
  .github/workflows/tests-integration-mainnet.yml
  .github/workflows/tests-integration-scratch.yml
  package.json
  yarn.lock
Labels: dependencies, ci/cd
