Repository lidofinance/core, pull requests merged in 2024-04, with the labels that each got.

#68 chore: update dependencies
  hardhat.config.ts
  package.json
  pnpm-lock.yaml
Labels: dependencies, typescript

#76 chore: update pnpm-lock.yaml to pnpm v9 format
  package.json
  pnpm-lock.yaml
Labels: bug, dependencies

#74 test: add tests for 0.4.24 libs
  lib/constants.ts
  lib/index.ts
  lib/signing-keys.ts
  test/0.4.24/contracts/Packed64x4__Harness.sol
  test/0.4.24/contracts/SigningKeys__Harness.sol
  test/0.4.24/lib/packed64x4.t.sol
  test/0.4.24/lib/packed64x4.test.ts
  test/0.4.24/lib/signingKeys.test.ts
Labels: tests

#70 Base oracle tests
  .gitignore
  test/0.8.9/contracts/MockConsensusContract.sol
  test/0.8.9/oracle/baseOracle.ts
  test/0.8.9/oracle/baseOracleAccessControl.test.ts
  test/0.8.9/oracle/baseOracleSetConsensus.test.ts
  test/0.8.9/oracle/baseOracleSubmitReport.test.ts
Labels: tests

#75 Port of Sanity check tests
  lib/time.ts
  test/0.8.9/sanityChecks/baseOracleReportSanityChecker.test.ts
Labels: tests
