Repository lidofinance/core, pull requests merged in 2024-05, with the labels that each got.

#87 Weekly PR: moving to yarn
  .gitattributes
  .github/workflows/analyse.yml
  .github/workflows/coverage.yml
  .github/workflows/linters.yml
  .github/workflows/tests.yml
  .gitignore
  .husky/commit-msg
  .husky/pre-commit
  .prettierignore
  .solcover.js
  .yarnrc.yml
  CONTRIBUTING.md
  package.json
  pnpm-lock.yaml
  scripts/scratch/dao-deploy.sh
  scripts/scratch/dao-local-deploy.sh
  yarn.lock
Labels: dependencies

#90 docs: some details for setting up yarn
  CONTRIBUTING.md
  package.json
  yarn.lock
Labels: documentation, dependencies

#88 Feat: positive token rebase limiter fuzz tests
  contracts/0.8.9/test_helpers/PositiveTokenRebaseLimiterMock.sol
  test/0.8.9/positiveTokenRebaseLimiter.t.sol
Labels: tests, solidity

#83 Accounting oracle tests
  lib/dummy.ts
  lib/oracle.ts
  lib/string.ts
  test/0.4.24/contracts/LidoLocator__MutableMock.sol
  test/0.4.24/lido/lido.handleOracleReport.test.ts
  test/0.8.9/contracts/oracle/AccountingOracleTimeTravellable.sol
  test/0.8.9/contracts/oracle/BaseOracleTimeTravellable.sol
  test/0.8.9/contracts/oracle/HashConsensusTimeTravellable.sol
  test/0.8.9/contracts/oracle/MockLidoForAccountingOracle.sol
  test/0.8.9/contracts/oracle/MockReportProcessor.sol
  test/0.8.9/contracts/oracle/MockStakingRouterForAccountingOracle.sol
  test/0.8.9/contracts/oracle/MockWithdrawalQueueForAccoutingOracle.sol
  test/0.8.9/contracts/oracle/ValidatorsExitBusTimeTravellable.sol
  test/0.8.9/oracle/accountingOracleAccessControl.test.ts
  test/0.8.9/oracle/accountingOracleDeploy.test.ts
  test/0.8.9/oracle/accountingOracleHappyPath.test.ts
  test/0.8.9/oracle/accountingOracleSubmitReport.test.ts
  test/0.8.9/oracle/accountingOracleSubmitReportExtraData.test.ts
  test/0.8.9/oracle/baseOracle.ts
  test/0.8.9/oracle/baseOracleAccessControl.test.ts
  test/0.8.9/oracle/baseOracleSubmitReport.test.ts
  test/0.8.9/oracle/hashConsensus.ts
Labels: typescript, tests

#82 Staking router test fixes
  test/0.8.9/contracts/StakingModule__Mock.sol
  test/0.8.9/stakingRouter/stakingRouter.misc.test.ts
  test/0.8.9/stakingRouter/stakingRouter.module-management.test.ts
  test/0.8.9/stakingRouter/stakingRouter.module-sync.test.ts
  test/0.8.9/stakingRouter/stakingRouter.rewards.test.ts
  test/0.8.9/stakingRouter/stakingRouter.status-control.test.ts
Labels: typescript, tests
